APPS/HomePage/urls.py
from django.urls import path
from . import views


app_name = 'homepage'
urlpatterns = [
    path('home/',views.home,name='home'),
    path('',views.index,name='index'),
    path('selfins/',views.selfins,name='selfins'),
    path('teamins/',views.teamins,name='teamins'),
    path('blog/',views.blog,name='blog'),
    path('blogdetial/',views.blogdetial,name='blogdetial'),
    path('inshelp/',views.inshelp,name='inshelp'),
    path('contact/',views.contact,name='contact'),
    path('customins/',views.customins,name='customins'),
    path('test/',views.test,name='test'),
    path('logout/',views.logout,name='logout'),

]

APPS/welcome/urls.py
from django.urls import path
from . import views


app_name = 'welcome'
urlpatterns = [
    path('index/',views.index,name='index'),
    path('',views.index),
    path('login/',views.login,name='login'),
    path('signup/',views.signup,name='signup')
]

ActuarialSystem/urls.py
from django.contrib import admin
from django.urls import path, include

admin.site.login_bg = 'https://pic4.zhimg.com/v2-73b8307b2db44c617f4e8515ce67dd39_r.jpg'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('homepage/', include('APPS.HomePage.urls',namespace='homepage')),
    path('welcome/',include('APPS.welcome.urls',namespace='welcome')),
    path('',include('APPS.welcome.urls')),
    
]

model/models.py
# -*- coding:utf-8 -*-
from django.db import models

# Create your models here.
class User(models.Model):
    user_id = models.CharField(primary_key=True,  verbose_name='用户ID', max_length=10)
    user_name = models.CharField(unique=True, verbose_name='用户名', max_length=20)
    user_password = models.CharField(max_length=20)
    user_type = models.ForeignKey('UserType', models.DO_NOTHING, db_column='user_type')
    user_gender = models.IntegerField(blank=True, null=True,verbose_name='性别',)
    user_phone = models.CharField(max_length=20, blank=True, null=True,verbose_name='电话',)
    user_email = models.CharField(unique=True, max_length=40, blank=True, null=True,verbose_name='邮箱',)
    user_icon = models.CharField(max_length=255, blank=True, null=True)

    class Meta:

        db_table = 'user'
        verbose_name_plural = '用户表'

class UserType(models.Model):
    usertype_id = models.IntegerField(primary_key=True,default=1)
    usertype_name = models.CharField(max_length=255)

    class Meta:

        db_table = 'user_type'
        verbose_name_plural = '用户类型表'

class Insurance(models.Model):
    ins_id = models.CharField(primary_key=True, max_length=10)
    ins_initiator_id = models.CharField(max_length=10)
    ins_type = models.ForeignKey('InsuranceType', models.DO_NOTHING, db_column='ins_type')
    ins_name = models.CharField(max_length=255)
    ins_pay = models.CharField(max_length=255)
    ins_profit = models.CharField(max_length=255)
    # ins_picture = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'insurance'
        verbose_name_plural = '保险表'


class InsuranceType(models.Model):
    instype_id = models.IntegerField(primary_key=True)
    instype_name = models.CharField(max_length=255)

    class Meta:
        managed = False
        db_table = 'insurance_type'
        verbose_name_plural = '保险类型表'

class Post(models.Model):
    post_id = models.CharField(primary_key=True, max_length=10)
    post_time = models.DateTimeField()
    post_name = models.CharField(max_length=255)
    post_info = models.CharField(max_length=255, blank=True, null=True)
    post_looked = models.IntegerField(blank=True, null=True)
    post_lmsg = models.CharField(max_length=255, blank=True, null=True)
    post_type = models.CharField(max_length=50)
    post_picurl = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'post'
        verbose_name_plural = '帖子表'



class PostType(models.Model):
    post_type_id = models.CharField(primary_key=True, max_length=10)
    post_type_name = models.CharField(max_length=20)

    class Meta:
        managed = False
        db_table = 'post_type'
        verbose_name_plural = '帖子类型表'

class InsuranceSubtype(models.Model):
    ins_subtype_id = models.CharField(primary_key=True, max_length=10)
    ins_subtype_name = models.CharField(max_length=255)
    instype = models.ForeignKey('InsuranceType', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'insurance_subtype'
        verbose_name_plural = '保险sub'


class Blog(models.Model):
    blog_id = models.CharField(primary_key=True, max_length=10)
    blog_name = models.CharField(max_length=50)
    blog_icon = models.CharField(max_length=100, blank=True, null=True)
    blog_date = models.DateTimeField()
    blog_msg = models.CharField(max_length=255, blank=True, null=True)
    blog_visited = models.CharField(max_length=10, blank=True, null=True)
    blog_comment = models.CharField(max_length=10, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'blog'
        verbose_name_plural = '帖子'

APPS/HomePage/views.py
from django.shortcuts import render
from model.models import Blog
from django.http import HttpResponseRedirect
# Create your views here.
from model import models

def home(requests):
    return render(requests, 'homepage/index.html')

def index(requests):
    return render(requests,'homepage/index.html')

def selfins(requests):
    return render(requests,'homepage/selfins.html')

def teamins(requests):
    s = requests.session
    return render(requests,'homepage/teamins.html')

def inshelp(requests):
    return render(requests,'homepage/inshelp.html')

def blog(requests):
    blogs = Blog.objects.all()
    return render(requests,'homepage/blog.html',{'blogs':blogs})

def blogdetial(requests):
    return render(requests, 'homepage/blogdetial.html')

def contact(requests):
    return render(requests,'homepage/contact.html')

def customins(requests):
    return render(requests,'homepage/customins.html')

def test(requests):
    return render(requests,'homepage/ddddddd.html')

def logout(requests):
    # 删除当前会话的session
    requests.session.flush()
    return render(requests,'welcome/index.html')

APPS/welcome/views.py
from django.shortcuts import render

from APPS.welcome import utils
from model.models import User, UserType
import random

# Create your views here.
def index(requests):
    return render(requests,'welcome/index.html')


def login(requests):
    name = requests.POST.get('name')
    password = requests.POST.get('password')
    user = User.objects.filter(user_name=name,user_password=password)
    if user:
        # 添加session 一周后过期
        requests.session['id'] = user[0].user_id
        requests.session['name'] = user[0].user_name
        requests.session.set_expiry(604800)
        return render(requests,'homepage/index.html')
    else:
        return render(requests,'welcome/index.html',{'Msg':'账号名或密码输入错误，请重新输入'})


def signup(requests):
    name = requests.POST.get('name')
    pwd = requests.POST.get('password')
    mail = requests.POST.get('email')
    id = utils.utils.get_random_user_id()
    type = UserType(usertype_id=0,usertype_name='管理员')
    try:
        user = User.objects.create(user_id=id, user_name=name, user_password=pwd, user_type=type, user_gender=0,
                    user_email=mail)
    except:
        return render(requests,'welcome/index.html',{'Msg':'账号注册发生异常，请重新尝试'})
    else:
        requests.session['id'] = id
        requests.session['name'] = name
        requests.session.set_expiry(604800)
        return render(requests, 'homepage/index.html')

model/views.py
from django.shortcuts import render

# Create your views here.

templates/homepage/blog.html
{% extends 'homepage/template.html' %}
{% block mainbody %}
  <!--================Blog Area =================-->
  <section class="blog_area area-padding">
      <div class="container">
          <div class="row">
              <div class="col-lg-8 mb-5 mb-lg-0">
                  <div class="blog_left_sidebar">
                      {% for item in blogs %}
                      <article class="blog_item">
                        <div class="blog_item_img"><a href="{% url 'homepage:blogdetial' %}">
                          <img class="card-img rounded-0" src="../../static/img/{{item.blog_icon}}" alt="" ></a>
                          <a href="{% url 'homepage:blogdetial' %}" class="blog_item_date">
                            <h3>{{item.blog_date.day}}</h3>
                            <p>{{ item.blog_date.month }}月</p>
                          </a>
                        </div>
                        
                        <div class="blog_details">
                            <a class="d-inline-block" href="{% url 'homepage:blogdetial' %}">
                                <h2>{{ item.blog_name }}</h2>
                            </a>
                            <p>{{ item.blog_msg }}</p>
                            <ul class="blog-info-link">
                              <li><a href="{% url 'homepage:blogdetial' %}"><i class="far fa-user"></i>{{ item.blog_visited }}浏览</a></li>
                              <li><a href="{% url 'homepage:blogdetial' %}"><i class="far fa-comments"></i> {{ item.blog_comment }}评论</a></li>
                            </ul>
                        </div>
                      </article>
                      


                      {% endfor %}





                      


                      <nav class="blog-pagination justify-content-center d-flex">
                          <ul class="pagination">
                              <li class="page-item">
                                  <a href="#" class="page-link" aria-label="Previous">
                                      <i class="ti-angle-left"></i>
                                  </a>
                              </li>
                              <li class="page-item">
                                  <a href="#" class="page-link">1</a>
                              </li>
                              <li class="page-item active">
                                  <a href="#" class="page-link">2</a>
                              </li>
                              <li class="page-item">
                                  <a href="#" class="page-link" aria-label="Next">
                                      <i class="ti-angle-right"></i>
                                  </a>
                              </li>
                          </ul>
                      </nav>
                  </div>
              </div>
              <div class="col-lg-4">
                  <div class="blog_right_sidebar">
                      <aside class="single_sidebar_widget search_widget">
                          <form action="#">
                            <div class="form-group">
                              <div class="input-group mb-3">
                                <input type="text" class="form-control" placeholder="搜索关键字">
                                <div class="input-group-append">
                                  <button class="btn" type="button"><i class="ti-search"></i></button>
                                </div>
                              </div>
                            </div>
                            <button class="button rounded-0 primary-bg text-white w-100" type="submit">搜索</button>
                          </form>
                      </aside>

                      <aside class="single_sidebar_widget post_category_widget">
                        <h4 class="widget_title">分类</h4>
                        <ul class="list cat-list">
                            <li>
                                <a href="#" class="d-flex">
                                    <p>保险理赔</p>
                                    <p>(37)</p>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="d-flex">
                                    <p>保险细则</p>
                                    <p>(10)</p>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="d-flex">
                                    <p>经验分享</p>
                                    <p>(03)</p>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="d-flex">
                                    <p>保险选购</p>
                                    <p>(11)</p>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="d-flex">
                                    <p>保险意义</p>
                                    <p>(21)</p>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="d-flex">
                                    <p>保险收益</p>
                                    <p>(09)</p>
                                </a>
                            </li>
                        </ul>
                      </aside>

                      <aside class="single_sidebar_widget popular_post_widget">
                          <h3 class="widget_title">近期发帖</h3>
                          <div class="media post_item">
                              <img src="../../static/img/blog/popular-post/post1.jpg" alt="post">
                              <div class="media-body">
                                  <a href="blogdetial.html">
                                      <h3>选购保险的10个注意事项</h3>
                                  </a>
                                  <p>10分钟前</p>
                              </div>
                          </div>
                          <div class="media post_item">
                              <img src="../../static/img/blog/popular-post/post2.jpg" alt="post">
                              <div class="media-body">
                                  <a href="blogdetial.html">
                                      <h3>理赔的正确流程</h3>
                                  </a>
                                  <p>2小时前</p>
                              </div>
                          </div>
                          <div class="media post_item">
                              <img src="../../static/img/blog/popular-post/post3.jpg" alt="post">
                              <div class="media-body">
                                  <a href="blogdetial.html">
                                      <h3>教育保险的那些坑</h3>
                                  </a>
                                  <p>一天前</p>
                              </div>
                          </div>
                          <div class="media post_item">
                              <img src="../../static/img/blog/popular-post/post4.jpg" alt="post">
                              <div class="media-body">
                                  <a href="blogdetial.html">
                                      <h3>保险公司的流氓策略</h3>
                                  </a>
                                  <p>2020/9/11</p>
                              </div>
                          </div>
                      </aside>

                  </div>
              </div>
          </div>
      </div>
  </section>
  <!--================Blog Area =================-->
<div class="latest-news  area-padding-bottom">
        <div class="container">
            <div class="row">
                <div class="area-heading">
                    <h3>让生活更加多滋美味</h3>
                    <p>北邮太平  给您的生活带来更多保障</p>
                </div>

            </div>
        </div>
    </div>

<!-- ================ Instargram Area Starts ================= -->  

    <section class="instagram">
        <div class="row no-gutters">
            <div class="col-2">
                <a href=""><img src="../../static/img/instagram/1.jpg" alt=""></a>
            </div>
            <div class="col-2">
                <a href=""><img src="../../static/img/instagram/2.jpg" alt=""></a>
            </div>
            <div class="col-2">
                <a href=""><img src="../../static/img/instagram/3.jpg" alt=""></a>
            </div>
            <div class="col-2">
                <a href=""><img src="../../static/img/instagram/4.jpg" alt=""></a>
            </div>
            <div class="col-2">
                <a href=""><img src="../../static/img/instagram/5.jpg" alt=""></a>
            </div>
            <div class="col-2">
                <a href=""><img src="../../static/img/instagram/6.jpg" alt=""></a>
            </div>
        </div>
    </section>

    <!-- ================ Instargram Area End ================= -->  

{% endblock mainbody %}

templates/homepage/contact.html
{% extends 'homepage/template.html' %}

 {% block mainbody %}
<!-- Start Align Area -->
<div class="whole-wrap">
    <div class="container">
        <div class="section-top-border">
            <h3 class="mb-30 title_color">北邮太平来历</h3>
            <div class="row">
                <div class="col-md-3">
                    <img src="../../static/img/company2.jfif" alt="" class="img-fluid">
                </div>
                <div class="col-md-9 mt-sm-20 left-align-p">
                    <p>中国保险精算行业刚刚起步，处在与国际接轨阶段。在2019年中国总精算师论坛上，透露出一个至关重要的信息——当前保险业正在回归保障本源，产品方向和费率的调整需要保险精算师的出谋划策。然而当前，在国内185家保险公司中，有65家公司急缺总精算师，占比超35%。在这种情况下迫切需要一款专业的精算软件去协助精算师们提高精算师的工作效率和精准度，并为不同用户量身打造不同的投保方案，缓解精算师的工作压力。
基于上述情况，我们准备开发一款拥有自主版权的专业的保险精算软件来填补国内空白，解决当下精算师工作效率较低，并为不同用户量身打造不同的投保方案。
</p>
                </div>
            </div>
        </div>
        <div class="section-top-border text-right">
            <h3 class="mb-30 title_color">创新点与特色</h3>
            <div class="row">
                <div class="col-md-9">
                    <p class="text-right">目前国内急缺专业的保险精算软件，我们的保险精算系统恰能解决这个燃眉之急。而基于大数据的研发首先可以帮助保险公司从“样本精算”升级至“全量精算”，保险公司可以真正以客户为中心, 把客户分为成千上万种, 这样保险公司经营就完全可以实现差别费率, 对于风险低的客户敢于大胆降低费率, 对于风险高的客户提高费率甚至拒绝承保, 这样保险公司之间就可以实现真正的差异化竞争。其次大数据能够弱化用户与保险公司之间的部分不对称的信息，减少双方信息不对称的情况，从而减少保险欺诈的概率。</p>
                </div>
                <div class="col-md-3">
                    <img src="../../static/img/company1.jfif" alt="" class="img-fluid">
                </div>
            </div>
        </div>
        <div class="section-top-border">
            <h3 class="mb-30 title_color">功能优势</h3>
            <div class="row">
                <div class="col-md-4">
                    <div class="single-defination">
                        <h4 class="mb-20">定制化</h4>
                        <p>针对痛点，将精算算法的应用普及到个人，实现对个人的低预算保险定制，让个人购买保险不再摇摆不定，集成大量用户需求数据也有助于保险公司提高精算定价的准确性。</p>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="single-defination">
                        <h4 class="mb-20">深度比对</h4>
                        <p>利用精算结果，对在售保险进行性价比分析；基于比价系统以及客户个人信息，测算个性化保险配置；基于比价系统和个性化保险配置的产品评测系统。</p>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="single-defination">
                        <h4 class="mb-20">一对一服务</h4>
                        <p>保险公司推销人员也可使用个人精算定制服务，快速根据客户需求得到匹配度和性价比最高的产品，同时实现了保险公司产品接口的接入，完成精算定制之后用户即可进行保险购买，实现产品商业化。</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="section-top-border">
            <h3 class="mb-30 title_color">项目前景</h3>
            <div class="row">
                <div class="col-lg-12">
                    <blockquote class="generic-blockquote">
                        精算是干什么的?主流的来说，精算就是开发保险产品，然后为保险公司保驾护航的。因为保险是现在把钱收进来，用于未来的赔付，所以保险产品在定价时必须基于现有假设的统计模型制定出合理的价格，在销售之后精算师还要负责把收进来的钱进行整理，哪些花在赔付的保险金，哪些花给了公司运作，甚至还要根据对未来现金流的评估，提出一部分钱分给股东。有句调侃叫“精算师并不产生利润，他们只是利润的搬运工”，这并不全对，但核心意思大概就是这样。
在国内185家保险公司中，有65家公司急缺总精算师，占比超35%。在这种情况下迫切需要一款专业的精算软件去协助精算师们提高精算师的工作效率和精准度，并为不同用户量身打造不同的投保方案，缓解精算师的工作压力。
目前，国内的精算软件市场几乎没有被开发。国外引进的精算软件，而且使用起来比较复杂，上手门槛较高，编程灵活度有限，且版权费用较高。因此，国内的保险精算软件市场急需去填补空白。
                        保险精算比价:
将精算算法结合保险打破垄断，将精算算法的应用普及到个人，不仅对个人实现低预算保险定制提供了实现的可能，让个人购买保险不再隔雾看花，搜集到的用户需求数据也可以帮助保险公司提高精算定价的准确性。这对市场中的买方和卖方都有利。 经调查得知目前国内保险市场有类似的比价产品，基本上品类单一，只有比价功能但没有精算定制。对于一款能够面向大众的智能化精算定价软件，市场需求是非常高的，因此精算定制功能市场可行性比较高。
精算功能:
由《中国精算与风险管理报告》表面，我国精算产品受国外软件垄断，本软件最终算法实现后可以打破市场垄断。精算软件在我国市场稀缺，大多为国外软件，因此精算功能的市场可行性很高。
                        </blockquote>
                </div>
            </div>
        </div>

    </div>
</div>
<!-- End Align Area -->
{% endblock  %}

templates/homepage/inshelp.html
{% extends 'homepage/template.html' %}
{% block mainbody%}
    <script src="{% static 'SpreadJS/scripts/gc.spread.sheets.all.14.0.6.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'SpreadJS/scripts/gc.spread.sheets.designer.resource.cn.14.0.6.min.js' %}" type="text/javascript"></script>
    <link href="{% static 'SpreadJS/css/gc.spread.sheets.excel2016colorful.14.0.6.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'SpreadJS/css/gc.spread.sheets.designer.14.0.6.min.css' %}" rel="stylesheet" type="text/css"/>

    <script type="text/javascript">
    window.onload = function(){
        var spread = new GC.Spread.Sheets.Workbook(document.getElementById("ss"),{sheetCount:3});
        var sheet = spread.getActiveSheet();


    }
    </script>

    <div id="ss" style="height: 600px; width: 70%; margin: 0 auto;" ></div>

{% endblock %}

templates/homepage/template.html
 <!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" href="../../static/img/favicon.png" type="image/png">
    <title>Eden Megazine</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="../../static/css/bootstrap.css">
    <link rel="stylesheet" href="../../static/css/themify-icons.css">
    <link rel="stylesheet" href="../../static/css/flaticon.css">
{#    <link rel="stylesheet" href="../../static/vendors/fontawesome/css/all.min.css">#}
    <link rel="stylesheet" href="../../static/vendors/animate-css/animate.css">
    <link rel="stylesheet" href="../../static/vendors/popup/magnific-popup.css">
    <!-- main css -->
    <link rel="stylesheet" href="../../static/css/style.css">
    <link rel="stylesheet" href="../../static/css/responsive.css">
    <link href="https://cdn.bootcdn.net/ajax/libs/font-awesome/5.9.0/css/all.min.css" rel="stylesheet">

</head>
<body>

    <!--================ Start header Top Area =================-->
    <section class="header-top" style="background-color: #6f42c1">

            <div class="row align-items-center justify-content-between" >
                <div class="col-6 col-lg-4 col-md-6 col-sm-6 logo-wrapper">
                    <a href="index.html" class="logo">
                        <img src="../../static/img/logo.png" alt="">
                    </a>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-6 search-trigger">
                    <div class="right-button" style="text-align: center">
                        <ul>
                            <li><a id="search" href="javascript:void(0)"><i class="fas fa-search" style="color: #9fcdff"></i></a></li>
                            <li><a href="" style="color: #9fcdff">你好!&nbsp;&nbsp;{{ request.session.name}}</a></li>
                            <li><a href="{% url 'homepage:logout' %}" style="color: #9fcdff">登出</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        <div class="search_input" id="search_input_box">
            <div class="container ">
                <form class="d-flex justify-content-between search-inner">
                    <input type="text" class="form-control" id="search_input" placeholder="Search Here">
                    <button type="submit" class="btn"></button>
                    <span class="ti-close" id="close_search" ></span>
                </form>
            </div>
        </div>
    </section>
    <!--================ End header top Area =================-->

    <!-- Start header Menu Area -->
    <header id="header" class="header_area">
        <div class="main_menu">
            <nav class="navbar navbar-expand-lg navbar-light">
                <div class="container">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse offset" id="navbarSupportedContent">
                        <ul class="nav navbar-nav menu_nav ml-auto mr-auto">
                            <li class="nav-item"><a class="nav-link" href="{% url 'homepage:index' %}" style="font-size: 20px">主页</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'homepage:selfins' %} "style="font-size: 20px">个人保险</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'homepage:teamins' %}" style="font-size: 20px">团体保险</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'homepage:customins' %}" style="font-size: 20px">定制保险</a></li>
                             <li class="nav-item"><a class="nav-link" href="{% url 'homepage:blog' %}" style="font-size: 20px">保险论坛</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'homepage:inshelp' %}" style="font-size: 20px">精算辅助</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'homepage:contact' %}" style="font-size: 20px">关于我们</a></li>
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
    </header>
    <!-- End header MEnu Area -->
    {% block   mainbody%}
    {% endblock mainbody %}


</br></br></br>
    <!-- ================ start footer Area ================= -->
    <footer class="footer-area">
        <div class="container">
            <div class="row">

                <div class="col-lg-3 col-sm-6 mb-4 mb-xl-0 single-footer-widget">
                    <h4>关于我们</h4>
                    <p>北邮太平，打造专属您的定制化保险服务</p>
                    <div class="footer-logo">
                        <img src="../../static/img/logo.png" alt="">
                    </div>
                </div>

                <div class="col-lg-3 col-sm-6 mb-4 mb-xl-0 single-footer-widget">
                    <h4>联系资料</h4>
                    <div class="footer-address">
                        <p>地址 :北京邮电大学西土城校区</p>
                        <span>电话 : +8880 44338899</span>
                        <span>邮箱 : bytp@bupt.edu.cn</span>
                    </div>
                </div>

                <div class="col-lg-3 col-sm-6 mb-4 mb-xl-0 single-footer-widget">
                    <h4>友情链接</h4>
                    <ul>
                        <li><a href="{% url 'homepage:selfins' %}">个人优质险</a></li>
                        <li><a href="{% url 'homepage:teamins' %}">经济团体险</a></li>
                        <li><a href="{% url 'homepage:contact' %}">关于我们</a></li>
                        <li><a href="https://www.chinalife.com.cn/chinalife/index/" target="_blank">中国人寿</a></li>
                        <li><a href="http://www.cpic.com.cn/" target="_blank">太平洋人寿</a></li>
                    </ul>
                </div>

                <div class="col-lg-3 col-sm-6 col-md-6 mb-4 mb-xl-0 single-footer-widget">
                    <h4>发送邮件</h4>
                    <p>如果您遇到问题，可留下您的邮箱，我们将尽快联系您</p>

                    <div class="form-wrap" id="mc_embed_signup">
                        <form target="_blank" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
                        method="get">
                        <div class="input-group">
                            <input type="email" class="form-control" name="EMAIL" placeholder="邮箱地址" onfocus="this.placeholder = ''" onblur="this.placeholder = '邮箱地址 '">
                            <div class="input-group-append">
                                <button class="btn click-btn" type="submit">
                                    <i class="fab fa-telegram-plane"></i>
                                </button>
                            </div>
                        </div>
                        <div style="position: absolute; left: -5000px;">
                            <input name="b_36c4fd991d266f23781ded980_aefe40901a" tabindex="-1" value="" type="text">
                        </div>

                        <div class="info"></div>
                    </form>
                </div>

            </div>
        </div>
        <div class="footer-bottom row align-items-center text-center  no-gutters">
            <p class="footer-text m-0 col-lg-8 col-md-12"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | 北邮太平
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>

        </div>
    </div>
</footer>
<!-- ================ End footer Area ================= -->

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="../../static/js/jquery-2.2.4.min.js"></script>
<script src="../../static/js/popper.js"></script>
<script src="../../static/js/bootstrap.min.js"></script>
<script src="../../static/js/stellar.js"></script>
<script src="../../static/vendors/popup/jquery.magnific-popup.min.js"></script>
<script src="../../static/js/jquery.ajaxchimp.min.js"></script>
<script src="../../static/js/waypoints.min.js"></script>
<script src="../../static/js/mail-script.js"></script>
<script src="../../static/js/contact.js"></script>
<script src="../../static/js/jquery.form.js"></script>
<script src="../../static/js/jquery.validate.min.js"></script>
<script src="../../static/js/mail-script.js"></script>
<script src="../../static/js/theme.js"></script>
</body>
</html>